-- MySQL Script generated by MySQL Workbench
-- Sun May 13 18:45:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mredgedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mredgedb` DEFAULT CHARACTER SET utf8 ;
USE `mredgedb` ;

-- -----------------------------------------------------
-- Table `mredgedb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mredgedb`.`customer` (
  `customer_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `address3` VARCHAR(45) NULL,
  `county` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mredgedb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mredgedb`.`booking` (
  `booking_id` INT NOT NULL,
  `current_date` DATE NULL,
  `preferred_date` DATE NULL,
  `knives` INT NULL,
  `rate1` DECIMAL NULL,
  `rate2` DECIMAL NULL,
  `price` DECIMAL NULL,
  `notes` VARCHAR(255) NULL,
  PRIMARY KEY (`booking_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mredgedb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mredgedb`.`contact` (
  `contact_id` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `job_title` VARCHAR(45) NULL,
  `notes` VARCHAR(255) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `fk_contact_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_contact_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mredgedb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mredgedb`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mredgedb`.`job` (
  `job_id` INT NOT NULL,
  `date` DATE NULL,
  `knives` INT NULL,
  `payment` DECIMAL NOT NULL,
  `notes` VARCHAR(255) NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mredgedb`.`job_for_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mredgedb`.`job_for_customer` (
  `job_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`job_id`, `customer_id`),
  INDEX `fk_job_has_customer_customer1_idx` (`customer_id` ASC),
  INDEX `fk_job_has_customer_job_idx` (`job_id` ASC),
  CONSTRAINT `fk_job_has_customer_job`
    FOREIGN KEY (`job_id`)
    REFERENCES `mredgedb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_has_customer_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mredgedb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mredgedb`.`customer_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mredgedb`.`customer_booking` (
  `booking_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`booking_id`, `customer_id`),
  INDEX `fk_booking_has_customer_customer1_idx` (`customer_id` ASC),
  INDEX `fk_booking_has_customer_booking1_idx` (`booking_id` ASC),
  CONSTRAINT `fk_booking_has_customer_booking1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `mredgedb`.`booking` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_has_customer_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mredgedb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
